version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      target: development
    ports:
      - '8080:8080'
    command: npm run start:dev
    env_file:
      - ./.env
